GET http://localhost:3000/users

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Emil",
    "password": "password"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "name": "Emil",
    "password": "password"
}